port: 8080
httpsPort: 8443
letsEncrypt:
  email: "test@example.com"
  staging: true
  certDir: "./certs"

routes:
  - domain: "example.com"
    target: "http://localhost:3000"
    ssl: true
  - domain: "test.example.com"
    target: "http://localhost:3001"
    ssl: true
  - domain: "api.example.com"
    target: "http://localhost:3002"
    ssl: true

processManagement:
  processes:
    test-app:
      enabled: true
      name: "Test Application"
      command: "node"
      args: ["-e", "console.log('Test app running'); setInterval(() => {}, 1000);"]
      restartOnExit: true
      restartDelay: 1000
      maxRestarts: 3 