#!/usr/bin/env zsh
. ~/.zprofile
. ~/.zshrc
. ~/.zshenv
setopt nohup nocheckjobs
for i in "comics" "bds" "photos"
do
  while (true)
  do
  cd  /Users/turpault/dev/bdreader-server
  DEBUG="comicus:*" npm run dev -- --config /Users/turpault/ComicusConfigs/config-$i >>/tmp/$i.log 2>&1
  echo "======================================================================" >> /tmp/$i.log
  sleep 10
  done &
done
xteve --port=2600 > /tmp/xteve.log 2>&1 &
echo "Running hourly jobs"
for i in 1.1.1.1 192.168.101.28
do
cat <<EOF >/tmp/$i.sh
ping -i 60 $i | while read line
do 
echo \`date\` \$i  - \$line
done
EOF
chmod 755 /tmp/$i.sh
open -a Terminal /tmp/$i.sh
done

while (true)
do
/usr/bin/python3 /Users/turpault/josstools/gandi/src/gandi-live-dns.py

sleep 3600
done
